#!/usr/bin/env python3
from __future__ import annotations

import argparse
import secrets
import stat
import string
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / ".env"
SECRET_LENGTH = 64
ALPHABET = string.ascii_letters + string.digits


def random_secret(length: int = SECRET_LENGTH) -> str:
    return "".join(secrets.choice(ALPHABET) for _ in range(length))


def build_env(*, app_env: str) -> str:
    values = {
        "APP_ENV": app_env,
        "SERVICE_BASE64_64_APP_ENCRYPTION_KEY": random_secret(),
        "SERVICE_BASE64_64_DASHBOARD_JWT_SECRET": random_secret(),
        "SERVICE_BASE64_64_PUBLIC_JWT_SECRET": random_secret(),
        "DASHBOARD_JWT_TTL_SECONDS": "28800",
        "DASHBOARD_ASSET_DIR": "/app/data/dashboard-assets",
        "SERVICE_PASSWORD_64_POSTGRES": random_secret(),
        "REDIS_URL": "redis://redis:6379/0",
        "SERVICE_PASSWORD_64_CLICKHOUSE": random_secret(),
    }
    sections = [
        ("Runtime", ["APP_ENV"]),
        (
            "Application secrets",
            [
                "SERVICE_BASE64_64_APP_ENCRYPTION_KEY",
                "SERVICE_BASE64_64_DASHBOARD_JWT_SECRET",
                "SERVICE_BASE64_64_PUBLIC_JWT_SECRET",
            ],
        ),
        (
            "Dashboard",
            ["DASHBOARD_JWT_TTL_SECONDS", "DASHBOARD_ASSET_DIR"],
        ),
        ("Postgres", ["SERVICE_PASSWORD_64_POSTGRES"]),
        ("Redis", ["REDIS_URL"]),
        ("ClickHouse", ["SERVICE_PASSWORD_64_CLICKHOUSE"]),
    ]

    lines = [
        "# Generated by scripts/generate-env.py.",
        "# Keep this file private; it contains stable deployment secrets.",
    ]
    for title, keys in sections:
        lines.append("")
        lines.append(f"# {title}")
        lines.extend(f"{key}={values[key]}" for key in keys)
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a secure Passport Auth .env file.")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Path to write. Defaults to {DEFAULT_OUTPUT}.",
    )
    parser.add_argument(
        "--app-env",
        choices=("development", "production"),
        default="development",
        help="APP_ENV value to write.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing output file.",
    )
    args = parser.parse_args()

    output = args.output
    if output.exists() and not args.force:
        raise SystemExit(f"{output} already exists. Use --force to overwrite it.")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_env(app_env=args.app_env), encoding="utf-8")
    output.chmod(stat.S_IRUSR | stat.S_IWUSR)
    print(f"Wrote secure environment values to {output}")


if __name__ == "__main__":
    main()
